### ISSUE TITLE
getting particular nested fields not working using this fields  filtering

### ISSUE THREAD

**Issue by shafiyal** [wimglenn/djangorestframework-queryfields#23] opened 2019-06-21 10:13 UTC
My GET body  is like below:
GET : /images
```
 {
        "id": 1,
        "images": [
            {
                "image": "e3942bf0-6c6.png",
                "width": 353,
                "height": 200,
                "size": 168306,
                "aspect_ratio": 1.765,
                "rendition": null
            }
         ]
}
```

I want to filter only width and height fields i.e.,
GET:/images?fields=width,height

Expected result:

```
 {
                "width": 353,
                "height": 200
}
```
But i am unable to specify nested fields while filtering fields 
How can I acheive this??

**Comment by wimglenn** [comment] 2019-06-21 15:29
dupe of https://github.com/wimglenn/djangorestframework-queryfields/issues/8

**Closed as completed by wimglenn** 2019-06-21 15:29 UTC

**Comment by shafiyal** [comment] 2019-06-27 13:08
I have seen #8  but did not get any solution for my problem , can you please clarify whether the nested fields filtering is supported by this package or not?

**Comment by wimglenn** [comment] 2019-06-27 13:21
To clarify: nested field filtering is not supported by this package. It might be added at a later date.

**Comment by shafiyal** [comment] 2019-06-27 13:27
ok... Thanks

**Comment by yezyilomo** [comment] 2019-06-28 05:16
Well for the mean time you can try [django-restql](https://github.com/yezyilomo/django-restql).
